pipeline:
  build:
    image: node:alpine
    commands:
      - npm install --registry=https://registry.npm.taobao.org
      - cp ./themes/hueman/_config.yml.example ./themes/hueman/_config.yml
      - ./node_modules/.bin/hexo generate
  # publish:
  #   image: plugins/docker
  #   repo: index.boxlinker.com/boxlinker/blog
  #   tags: latest
  #   privileged: true
  #   environment:
  #   - PLUGIN_REGISTRY=index.boxlinker.com
  #   - PLUGIN_USERNAME=boxlinker
  #   - PLUGIN_PASSWORD=QAZwsx123
publish:
  environment:
  - PLUGIN_REGISTRY=index.boxlinker.com
  - PLUGIN_USERNAME=boxlinker
  - PLUGIN_PASSWORD=QAZwsx123
